services:

  postgres-server:
    image: postgres
    restart: always
    volumes:
      - ./dbData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="Winter2005"
  
  tg_bot:
    build: .
    restart: always
    depends_on:
      - postgres-server
    environment:
      - PG_PASSWORD="Winter2005"
    