name: Starting docker compose on linux virtual machine on azure

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: SSH into azure and stopping docker compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
            cd / && cd docker_project/github/workspace && docker compose down

    - name: Copy file to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "${{ github.workspace }}"
        target: "/docker_project"
         
    - name: SSH into Azure VM and starting docker compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd / && cd docker_project/github/workspace && docker compose up --build --detach
 
